### ISSUE TITLE
Change default "chapter" string for unknown chapters

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#357]
At the very least, we should titlecase this and come up with something less ambiguous.

**Comment by gioneill** [comment]
From my observation, it looks like the design was for the footer to fill in with the localized text "Current Chapter" under circumstances when there was no "title" for the chapter:
`[NSString stringWithFormat:@"Page %u of %u (%@)",
     pageIndex + 1,
     pageCount,
     title ? title : NSLocalizedString(@"ReaderViewControllerCurrentChapter", nil)];`

However, as far as I can tell this 'title' variable can never be nil and is set to the localized text "chapter" when the dictionary is first created in the calculateBookLength method:
`        [spineItemDict setObject:NSLocalizedString(@"chapter", nil) forKey:@"tocElementTitle"];`

Since I'm not able to setObject to nil under the second case, I'm thinking the safest thing to do is just copy/paste the title-cased localized string down.

**Comment by gioneill** [comment]
<img width="320" alt="footer location copy" src="https://cloud.githubusercontent.com/assets/6179695/24426680/5a547a68-13d6-11e7-81a3-28ac78f4fdd9.png">
