### ISSUE TITLE
Under unknown circumstances an accounts won't be in the accounts list until the 2nd time the VC loads

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/Simplified-iOS#544]

**Comment by gioneill** [comment]
Found the issue and can reproduce:
The issue was that the tableview was not refreshing its data if the user switched tabs and then came back to the accounts list in settings.

Swipe to delete libraries, only primary left
Add Instant Classics
Switch tab to Catalog, go to Icon and switch to Instant Classics
Go back go Settings Accounts List
Bug: Brooklyn Library will show back up in list

Now when deleting and performing same steps, the accounts re-appears in the accounts list.

**Comment by aferditamuriqi** [comment]
fixed https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
