### ISSUE TITLE
Download background bar color sometimes is not matching library color

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/Simplified-iOS#545]

**Comment by gioneill** [comment]
@aferditamuriqi Since now we are more strict about delaying when someone tries to quickly switch library accounts, I believe this issue will not occur. But I also can't remember the exact way to reproduce, can you remember?
I remember it was something like beginning downloads in one library and then quickly switching over to another in the My Books section?

**Comment by aferditamuriqi** [comment]
it's not the quickly switching though, it's more like when you cancel or a download failed etc. there are different scenarios which you need to test and figure out when that happens. that was the main issue figuring out when it actually happens. unfortunately this is not fixed by the delay in switching between libraries.

**Comment by gioneill** [comment]
Issue was due to the fact that cell's being re-used in the function NYPLBookCellDequeue() were not resetting the background color.

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
