### ISSUE TITLE
update content mode on image view in accounts list controller

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/Simplified-iOS#613]
currently content mode is set to ".center" which will require the library logos to be exact size in order to not scale up. since logos are being provided later on from the library registry, this could cause UI issues.  
possible that frame size needs to be added as well.

**Comment by gioneill** [comment]
In NYPLSettingsAccountsList.swift

![simulator screen shot aug 2 2017 10 27 13 am](https://user-images.githubusercontent.com/6179695/28878431-4c0a30b0-776d-11e7-897e-6d07cb15d7b2.png)

Double check the UIImageViews in the accounts list to make sure their contentMode property is correctly set so that larger or smaller images still look roughly equal to each other.

One test would be to temporarily replace a library logo with one that is smaller, and one that is bigger, to make sure they still look good. Since other SimplyE partners will be adding these assets at other times we want it to look good without much designer intervention.
