### ISSUE TITLE
SettingsAccountAgeCheckbox error not localized

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/Simplified-iOS#621]
SettingsAccountAgeCheckbox  When not checked the app throws an error for folsk previously logged in but who did not check this box.

**Comment by gioneill** [comment]
On iOS any new strings that were being added would be showing up as the "Key" like James is reporting here, while the user is in a non-english system language.

I've gone back to October, since the translations were added in, and made sure that for any strings that have been added since then, we have the english version present on all four of our supported languages. This is a sensible placeholder until these new strings are also translated.
