### ISSUE TITLE
User Loses Current Reading Position in Book

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#688]
There are many times from beta testers and store reviews that report a loss of "current reading position" in a book. It's unknown if this is the result every time, but it has been reported that the position will back up to the beginning of the chapter.

Potential issues might be in saving to the book registry, OR the implementation of CFI-related javascript in the readium-shared-js repo.

Related to #603

**Comment by gioneill** [comment]
My first test confirms that failing to save the book registry is NOT correlated with the observed bug. If at any point the app quits without saving, then returning on the next launch will put the reader **_back to the last saved location_** (not the beginning of the chapter).

**Comment by matwood** [comment]
Have you tested using an EPUB that uses namespaces on tags internally? I recently fixed an issue in BiblioBoards Readium fork to handle tag namespacing because it was breaking CFI generation and usage (depending on the version of jquery used namespaced tags may or may not come back).

See the commit here: https://github.com/bibliolabs/readium-cfi-js/commit/b98069302df34cf5de08c303f2c0857dce968fe9

**Comment by gioneill** [comment]
This is likely due to a recently found crash while in the reader, and the client did not have a chance to write to disk, as our client design was only during "leaving the book" or "explicitly leaving/suspending the app".

Fixed in two important ways:
- Added an occassional save/write to disk while in a book.
- Introduction of server/cloud sync of reading position.
